use std::{
    collections::HashMap,
    ffi::{CString, c_char, c_void},
    io::{self, Write},
    sync::{Mutex, OnceLock},
};
use tracing::Level;
use tracing_subscriber::fmt::MakeWriter;

unsafe extern "C" {
    fn os_log_create(subsystem: *const c_char, category: *const c_char) -> *mut c_void;
    fn os_log_type_enabled(log: *mut c_void, log_type: u8) -> bool;
    fn _os_log_impl(
        dso: *mut c_void,
        log: *mut c_void,
        log_type: u8,
        format: *const c_char,
        buffer: *mut u8,
        size: u32,
    );
    static __dso_handle: u8;
}

const APPLE_LOG_SUBSYSTEM: &[u8] = b"com.nilssoncrypto.pkcs11rs\0";

// The format and buffer below reproduce os_log_with_type(log, type,
// "%{public}s", message) without requiring Clang at build time.
static APPLE_LOG_PUBLIC_STRING_FORMAT: [u8; 11] = *b"%{public}s\0";

const _: () = assert!(std::mem::size_of::<usize>() == 8);

#[derive(Clone, Copy)]
pub(crate) struct AppleMakeWriter;

pub(crate) struct AppleWriter {
    log: Option<usize>,
    log_type: u8,
    message: Vec<u8>,
}

impl<'writer> MakeWriter<'writer> for AppleMakeWriter {
    type Writer = AppleWriter;

    fn make_writer(&'writer self) -> Self::Writer {
        AppleWriter {
            log: apple_log("pkcs11rs"),
            log_type: apple_log_type(Level::TRACE),
            message: Vec::new(),
        }
    }

    fn make_writer_for(&'writer self, metadata: &tracing::Metadata<'_>) -> Self::Writer {
        AppleWriter {
            log: apple_log(metadata.target()),
            log_type: apple_log_type(*metadata.level()),
            message: Vec::new(),
        }
    }
}

impl Write for AppleWriter {
    fn write(&mut self, buffer: &[u8]) -> io::Result<usize> {
        self.message.extend_from_slice(buffer);
        Ok(buffer.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

impl Drop for AppleWriter {
    fn drop(&mut self) {
        while self
            .message
            .last()
            .is_some_and(|byte| matches!(byte, b'\r' | b'\n'))
        {
            self.message.pop();
        }
        let Some(log) = self.log else {
            return;
        };
        if self.message.is_empty() {
            return;
        }
        for byte in &mut self.message {
            if *byte == 0 {
                *byte = b'?';
            }
        }
        self.message.push(0);
        os_log_with_type(
            log as *mut c_void,
            self.log_type,
            self.message.as_ptr().cast::<c_char>(),
        );
    }
}

fn os_log_with_type(log: *mut c_void, log_type: u8, message: *const c_char) {
    if !unsafe { os_log_type_enabled(log, log_type) } {
        return;
    }

    // This is the encoding currently generated by Clang's
    // __builtin_os_log_format for one public C string. Bytes 0 and 1 are the
    // summary flags and command count; 0x22 and 8 describe a public string
    // whose value is an eight-byte pointer.
    let mut buffer = [0_u8; 12];
    buffer[..4].copy_from_slice(&[2, 1, 0x22, 8]);
    buffer[4..].copy_from_slice(&(message as usize).to_ne_bytes());

    unsafe {
        _os_log_impl(
            std::ptr::addr_of!(__dso_handle).cast_mut().cast::<c_void>(),
            log,
            log_type,
            APPLE_LOG_PUBLIC_STRING_FORMAT.as_ptr().cast::<c_char>(),
            buffer.as_mut_ptr(),
            buffer.len() as u32,
        );
    }
}

fn apple_log(target: &str) -> Option<usize> {
    static LOGS: OnceLock<Mutex<HashMap<String, usize>>> = OnceLock::new();
    let logs = LOGS.get_or_init(|| Mutex::new(HashMap::new()));
    let mut logs = match logs.lock() {
        Ok(logs) => logs,
        Err(poisoned) => poisoned.into_inner(),
    };
    if let Some(log) = logs.get(target) {
        return Some(*log);
    }
    let category = CString::new(target).ok()?;
    let log = unsafe {
        os_log_create(
            APPLE_LOG_SUBSYSTEM.as_ptr().cast::<c_char>(),
            category.as_ptr(),
        )
    };
    if log.is_null() {
        return None;
    }
    let log = log as usize;
    logs.insert(target.to_owned(), log);
    Some(log)
}

const fn apple_log_type(level: Level) -> u8 {
    const OS_LOG_TYPE_DEFAULT: u8 = 0x00;
    const OS_LOG_TYPE_INFO: u8 = 0x01;
    const OS_LOG_TYPE_DEBUG: u8 = 0x02;
    const OS_LOG_TYPE_ERROR: u8 = 0x10;

    match level {
        Level::ERROR => OS_LOG_TYPE_ERROR,
        Level::WARN => OS_LOG_TYPE_DEFAULT,
        Level::INFO => OS_LOG_TYPE_INFO,
        Level::DEBUG | Level::TRACE => OS_LOG_TYPE_DEBUG,
    }
}
