#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

/* automatically generated by rust-bindgen 0.59.2 */

pub const CRYPTOKI_VERSION_MAJOR: u32 = 2;
pub const CRYPTOKI_VERSION_MINOR: u32 = 40;
pub const CRYPTOKI_VERSION_REVISION: u32 = 0;
pub const CKN_SURRENDER: u32 = 0;
pub const CKF_TOKEN_PRESENT: u32 = 1;
pub const CKF_REMOVABLE_DEVICE: u32 = 2;
pub const CKF_HW_SLOT: u32 = 4;
pub const CKF_ARRAY_ATTRIBUTE: u32 = 1073741824;
pub const CKF_INTERFACE_FORK_SAFE: u32 = 1;
pub const CKF_RNG: u32 = 1;
pub const CKF_WRITE_PROTECTED: u32 = 2;
pub const CKF_LOGIN_REQUIRED: u32 = 4;
pub const CKF_USER_PIN_INITIALIZED: u32 = 8;
pub const CKF_RESTORE_KEY_NOT_NEEDED: u32 = 32;
pub const CKF_CLOCK_ON_TOKEN: u32 = 64;
pub const CKF_PROTECTED_AUTHENTICATION_PATH: u32 = 256;
pub const CKF_DUAL_CRYPTO_OPERATIONS: u32 = 512;
pub const CKF_TOKEN_INITIALIZED: u32 = 1024;
pub const CKF_SECONDARY_AUTHENTICATION: u32 = 2048;
pub const CKF_USER_PIN_COUNT_LOW: u32 = 65536;
pub const CKF_USER_PIN_FINAL_TRY: u32 = 131072;
pub const CKF_USER_PIN_LOCKED: u32 = 262144;
pub const CKF_USER_PIN_TO_BE_CHANGED: u32 = 524288;
pub const CKF_SO_PIN_COUNT_LOW: u32 = 1048576;
pub const CKF_SO_PIN_FINAL_TRY: u32 = 2097152;
pub const CKF_SO_PIN_LOCKED: u32 = 4194304;
pub const CKF_SO_PIN_TO_BE_CHANGED: u32 = 8388608;
pub const CK_EFFECTIVELY_INFINITE: u32 = 0;
pub const CK_INVALID_HANDLE: u32 = 0;
pub const CKU_SO: u32 = 0;
pub const CKU_USER: u32 = 1;
pub const CKU_CONTEXT_SPECIFIC: u32 = 2;
pub const CKS_RO_PUBLIC_SESSION: u32 = 0;
pub const CKS_RO_USER_FUNCTIONS: u32 = 1;
pub const CKS_RW_PUBLIC_SESSION: u32 = 2;
pub const CKS_RW_USER_FUNCTIONS: u32 = 3;
pub const CKS_RW_SO_FUNCTIONS: u32 = 4;
pub const CKF_RW_SESSION: u32 = 2;
pub const CKF_SERIAL_SESSION: u32 = 4;
pub const CKO_DATA: u32 = 0;
pub const CKO_CERTIFICATE: u32 = 1;
pub const CKO_PUBLIC_KEY: u32 = 2;
pub const CKO_PRIVATE_KEY: u32 = 3;
pub const CKO_SECRET_KEY: u32 = 4;
pub const CKO_HW_FEATURE: u32 = 5;
pub const CKO_DOMAIN_PARAMETERS: u32 = 6;
pub const CKO_MECHANISM: u32 = 7;
pub const CKO_VENDOR_DEFINED: u32 = 2147483648;
pub const CKH_MONOTONIC_COUNTER: u32 = 1;
pub const CKH_CLOCK: u32 = 2;
pub const CKH_USER_INTERFACE: u32 = 3;
pub const CKH_VENDOR_DEFINED: u32 = 2147483648;
pub const CKK_RSA: u32 = 0;
pub const CKK_DSA: u32 = 1;
pub const CKK_DH: u32 = 2;
pub const CKK_ECDSA: u32 = 3;
pub const CKK_EC: u32 = 3;
pub const CKK_X9_42_DH: u32 = 4;
pub const CKK_KEA: u32 = 5;
pub const CKK_GENERIC_SECRET: u32 = 16;
pub const CKK_RC2: u32 = 17;
pub const CKK_RC4: u32 = 18;
pub const CKK_DES: u32 = 19;
pub const CKK_DES2: u32 = 20;
pub const CKK_DES3: u32 = 21;
pub const CKK_CAST: u32 = 22;
pub const CKK_CAST3: u32 = 23;
pub const CKK_CAST128: u32 = 24;
pub const CKK_RC5: u32 = 25;
pub const CKK_IDEA: u32 = 26;
pub const CKK_SKIPJACK: u32 = 27;
pub const CKK_BATON: u32 = 28;
pub const CKK_JUNIPER: u32 = 29;
pub const CKK_CDMF: u32 = 30;
pub const CKK_AES: u32 = 31;
pub const CKK_BLOWFISH: u32 = 32;
pub const CKK_TWOFISH: u32 = 33;
pub const CKK_SHA_1_HMAC: u32 = 40;
pub const CKK_SHA256_HMAC: u32 = 43;
pub const CKK_SHA384_HMAC: u32 = 44;
pub const CKK_SHA512_HMAC: u32 = 45;
pub const CKK_SHA224_HMAC: u32 = 46;
pub const CKK_GOSTR3410: u32 = 48;
pub const CKK_GOSTR3411: u32 = 49;
pub const CKK_GOST28147: u32 = 50;
pub const CKK_VENDOR_DEFINED: u32 = 2147483648;
pub const CKC_X_509: u32 = 0;
pub const CKC_X_509_ATTR_CERT: u32 = 1;
pub const CKC_WTLS: u32 = 2;
pub const CKC_VENDOR_DEFINED: u32 = 2147483648;
pub const CKA_CLASS: u32 = 0;
pub const CKA_TOKEN: u32 = 1;
pub const CKA_PRIVATE: u32 = 2;
pub const CKA_LABEL: u32 = 3;
pub const CKA_APPLICATION: u32 = 16;
pub const CKA_VALUE: u32 = 17;
pub const CKA_OBJECT_ID: u32 = 18;
pub const CKA_CERTIFICATE_TYPE: u32 = 128;
pub const CKA_ISSUER: u32 = 129;
pub const CKA_SERIAL_NUMBER: u32 = 130;
pub const CKA_AC_ISSUER: u32 = 131;
pub const CKA_OWNER: u32 = 132;
pub const CKA_ATTR_TYPES: u32 = 133;
pub const CKA_TRUSTED: u32 = 134;
pub const CKA_CERTIFICATE_CATEGORY: u32 = 135;
pub const CKA_JAVA_MIDP_SECURITY_DOMAIN: u32 = 136;
pub const CKA_URL: u32 = 137;
pub const CKA_HASH_OF_SUBJECT_PUBLIC_KEY: u32 = 138;
pub const CKA_HASH_OF_ISSUER_PUBLIC_KEY: u32 = 139;
pub const CKA_NAME_HASH_ALGORITHM: u32 = 140;
pub const CKA_CHECK_VALUE: u32 = 144;
pub const CKA_KEY_TYPE: u32 = 256;
pub const CKA_SUBJECT: u32 = 257;
pub const CKA_ID: u32 = 258;
pub const CKA_SENSITIVE: u32 = 259;
pub const CKA_ENCRYPT: u32 = 260;
pub const CKA_DECRYPT: u32 = 261;
pub const CKA_WRAP: u32 = 262;
pub const CKA_UNWRAP: u32 = 263;
pub const CKA_SIGN: u32 = 264;
pub const CKA_SIGN_RECOVER: u32 = 265;
pub const CKA_VERIFY: u32 = 266;
pub const CKA_VERIFY_RECOVER: u32 = 267;
pub const CKA_DERIVE: u32 = 268;
pub const CKA_START_DATE: u32 = 272;
pub const CKA_END_DATE: u32 = 273;
pub const CKA_MODULUS: u32 = 288;
pub const CKA_MODULUS_BITS: u32 = 289;
pub const CKA_PUBLIC_EXPONENT: u32 = 290;
pub const CKA_PRIVATE_EXPONENT: u32 = 291;
pub const CKA_PRIME_1: u32 = 292;
pub const CKA_PRIME_2: u32 = 293;
pub const CKA_EXPONENT_1: u32 = 294;
pub const CKA_EXPONENT_2: u32 = 295;
pub const CKA_COEFFICIENT: u32 = 296;
pub const CKA_PUBLIC_KEY_INFO: u32 = 297;
pub const CKA_PRIME: u32 = 304;
pub const CKA_SUBPRIME: u32 = 305;
pub const CKA_BASE: u32 = 306;
pub const CKA_PRIME_BITS: u32 = 307;
pub const CKA_SUB_PRIME_BITS: u32 = 308;
pub const CKA_VALUE_BITS: u32 = 352;
pub const CKA_VALUE_LEN: u32 = 353;
pub const CKA_EXTRACTABLE: u32 = 354;
pub const CKA_LOCAL: u32 = 355;
pub const CKA_NEVER_EXTRACTABLE: u32 = 356;
pub const CKA_ALWAYS_SENSITIVE: u32 = 357;
pub const CKA_KEY_GEN_MECHANISM: u32 = 358;
pub const CKA_MODIFIABLE: u32 = 368;
pub const CKA_COPYABLE: u32 = 369;
pub const CKA_DESTROYABLE: u32 = 370;
pub const CKA_ECDSA_PARAMS: u32 = 384;
pub const CKA_EC_PARAMS: u32 = 384;
pub const CKA_EC_POINT: u32 = 385;
pub const CKA_SECONDARY_AUTH: u32 = 512;
pub const CKA_AUTH_PIN_FLAGS: u32 = 513;
pub const CKA_ALWAYS_AUTHENTICATE: u32 = 514;
pub const CKA_WRAP_WITH_TRUSTED: u32 = 528;
pub const CKA_GOSTR3410_PARAMS: u32 = 592;
pub const CKA_GOSTR3411_PARAMS: u32 = 593;
pub const CKA_GOST28147_PARAMS: u32 = 594;
pub const CKA_HW_FEATURE_TYPE: u32 = 768;
pub const CKA_RESET_ON_INIT: u32 = 769;
pub const CKA_HAS_RESET: u32 = 770;
pub const CKA_PIXEL_X: u32 = 1024;
pub const CKA_PIXEL_Y: u32 = 1025;
pub const CKA_RESOLUTION: u32 = 1026;
pub const CKA_CHAR_ROWS: u32 = 1027;
pub const CKA_CHAR_COLUMNS: u32 = 1028;
pub const CKA_COLOR: u32 = 1029;
pub const CKA_BITS_PER_PIXEL: u32 = 1030;
pub const CKA_CHAR_SETS: u32 = 1152;
pub const CKA_ENCODING_METHODS: u32 = 1153;
pub const CKA_MIME_TYPES: u32 = 1154;
pub const CKA_MECHANISM_TYPE: u32 = 1280;
pub const CKA_REQUIRED_CMS_ATTRIBUTES: u32 = 1281;
pub const CKA_DEFAULT_CMS_ATTRIBUTES: u32 = 1282;
pub const CKA_SUPPORTED_CMS_ATTRIBUTES: u32 = 1283;
pub const CKA_WRAP_TEMPLATE: u32 = 1073742353;
pub const CKA_UNWRAP_TEMPLATE: u32 = 1073742354;
pub const CKA_ALLOWED_MECHANISMS: u32 = 1073743360;
pub const CKA_VENDOR_DEFINED: u32 = 2147483648;
pub const CKM_RSA_PKCS_KEY_PAIR_GEN: u32 = 0;
pub const CKM_RSA_PKCS: u32 = 1;
pub const CKM_RSA_9796: u32 = 2;
pub const CKM_RSA_X_509: u32 = 3;
pub const CKM_MD2_RSA_PKCS: u32 = 4;
pub const CKM_MD5_RSA_PKCS: u32 = 5;
pub const CKM_SHA1_RSA_PKCS: u32 = 6;
pub const CKM_RIPEMD128_RSA_PKCS: u32 = 7;
pub const CKM_RIPEMD160_RSA_PKCS: u32 = 8;
pub const CKM_RSA_PKCS_OAEP: u32 = 9;
pub const CKM_RSA_X9_31_KEY_PAIR_GEN: u32 = 10;
pub const CKM_RSA_X9_31: u32 = 11;
pub const CKM_SHA1_RSA_X9_31: u32 = 12;
pub const CKM_RSA_PKCS_PSS: u32 = 13;
pub const CKM_SHA1_RSA_PKCS_PSS: u32 = 14;
pub const CKM_DSA_KEY_PAIR_GEN: u32 = 16;
pub const CKM_DSA: u32 = 17;
pub const CKM_DSA_SHA1: u32 = 18;
pub const CKM_DH_PKCS_KEY_PAIR_GEN: u32 = 32;
pub const CKM_DH_PKCS_DERIVE: u32 = 33;
pub const CKM_X9_42_DH_KEY_PAIR_GEN: u32 = 48;
pub const CKM_X9_42_DH_DERIVE: u32 = 49;
pub const CKM_X9_42_DH_HYBRID_DERIVE: u32 = 50;
pub const CKM_X9_42_MQV_DERIVE: u32 = 51;
pub const CKM_SHA256_RSA_PKCS: u32 = 64;
pub const CKM_SHA384_RSA_PKCS: u32 = 65;
pub const CKM_SHA512_RSA_PKCS: u32 = 66;
pub const CKM_SHA256_RSA_PKCS_PSS: u32 = 67;
pub const CKM_SHA384_RSA_PKCS_PSS: u32 = 68;
pub const CKM_SHA512_RSA_PKCS_PSS: u32 = 69;
pub const CKM_RC2_KEY_GEN: u32 = 256;
pub const CKM_RC2_ECB: u32 = 257;
pub const CKM_RC2_CBC: u32 = 258;
pub const CKM_RC2_MAC: u32 = 259;
pub const CKM_RC2_MAC_GENERAL: u32 = 260;
pub const CKM_RC2_CBC_PAD: u32 = 261;
pub const CKM_RC4_KEY_GEN: u32 = 272;
pub const CKM_RC4: u32 = 273;
pub const CKM_DES_KEY_GEN: u32 = 288;
pub const CKM_DES_ECB: u32 = 289;
pub const CKM_DES_CBC: u32 = 290;
pub const CKM_DES_MAC: u32 = 291;
pub const CKM_DES_MAC_GENERAL: u32 = 292;
pub const CKM_DES_CBC_PAD: u32 = 293;
pub const CKM_DES2_KEY_GEN: u32 = 304;
pub const CKM_DES3_KEY_GEN: u32 = 305;
pub const CKM_DES3_ECB: u32 = 306;
pub const CKM_DES3_CBC: u32 = 307;
pub const CKM_DES3_MAC: u32 = 308;
pub const CKM_DES3_MAC_GENERAL: u32 = 309;
pub const CKM_DES3_CBC_PAD: u32 = 310;
pub const CKM_CDMF_KEY_GEN: u32 = 320;
pub const CKM_CDMF_ECB: u32 = 321;
pub const CKM_CDMF_CBC: u32 = 322;
pub const CKM_CDMF_MAC: u32 = 323;
pub const CKM_CDMF_MAC_GENERAL: u32 = 324;
pub const CKM_CDMF_CBC_PAD: u32 = 325;
pub const CKM_MD2: u32 = 512;
pub const CKM_MD2_HMAC: u32 = 513;
pub const CKM_MD2_HMAC_GENERAL: u32 = 514;
pub const CKM_MD5: u32 = 528;
pub const CKM_MD5_HMAC: u32 = 529;
pub const CKM_MD5_HMAC_GENERAL: u32 = 530;
pub const CKM_SHA_1: u32 = 544;
pub const CKM_SHA_1_HMAC: u32 = 545;
pub const CKM_SHA_1_HMAC_GENERAL: u32 = 546;
pub const CKM_RIPEMD128: u32 = 560;
pub const CKM_RIPEMD128_HMAC: u32 = 561;
pub const CKM_RIPEMD128_HMAC_GENERAL: u32 = 562;
pub const CKM_RIPEMD160: u32 = 576;
pub const CKM_RIPEMD160_HMAC: u32 = 577;
pub const CKM_RIPEMD160_HMAC_GENERAL: u32 = 578;
pub const CKM_SHA256: u32 = 592;
pub const CKM_SHA256_HMAC: u32 = 593;
pub const CKM_SHA256_HMAC_GENERAL: u32 = 594;
pub const CKM_SHA384: u32 = 608;
pub const CKM_SHA384_HMAC: u32 = 609;
pub const CKM_SHA384_HMAC_GENERAL: u32 = 610;
pub const CKM_SHA512: u32 = 624;
pub const CKM_SHA512_HMAC: u32 = 625;
pub const CKM_SHA512_HMAC_GENERAL: u32 = 626;
pub const CKM_CAST_KEY_GEN: u32 = 768;
pub const CKM_CAST_ECB: u32 = 769;
pub const CKM_CAST_CBC: u32 = 770;
pub const CKM_CAST_MAC: u32 = 771;
pub const CKM_CAST_MAC_GENERAL: u32 = 772;
pub const CKM_CAST_CBC_PAD: u32 = 773;
pub const CKM_CAST3_KEY_GEN: u32 = 784;
pub const CKM_CAST3_ECB: u32 = 785;
pub const CKM_CAST3_CBC: u32 = 786;
pub const CKM_CAST3_MAC: u32 = 787;
pub const CKM_CAST3_MAC_GENERAL: u32 = 788;
pub const CKM_CAST3_CBC_PAD: u32 = 789;
pub const CKM_CAST5_KEY_GEN: u32 = 800;
pub const CKM_CAST128_KEY_GEN: u32 = 800;
pub const CKM_CAST5_ECB: u32 = 801;
pub const CKM_CAST128_ECB: u32 = 801;
pub const CKM_CAST5_CBC: u32 = 802;
pub const CKM_CAST128_CBC: u32 = 802;
pub const CKM_CAST5_MAC: u32 = 803;
pub const CKM_CAST128_MAC: u32 = 803;
pub const CKM_CAST5_MAC_GENERAL: u32 = 804;
pub const CKM_CAST128_MAC_GENERAL: u32 = 804;
pub const CKM_CAST5_CBC_PAD: u32 = 805;
pub const CKM_CAST128_CBC_PAD: u32 = 805;
pub const CKM_RC5_KEY_GEN: u32 = 816;
pub const CKM_RC5_ECB: u32 = 817;
pub const CKM_RC5_CBC: u32 = 818;
pub const CKM_RC5_MAC: u32 = 819;
pub const CKM_RC5_MAC_GENERAL: u32 = 820;
pub const CKM_RC5_CBC_PAD: u32 = 821;
pub const CKM_IDEA_KEY_GEN: u32 = 832;
pub const CKM_IDEA_ECB: u32 = 833;
pub const CKM_IDEA_CBC: u32 = 834;
pub const CKM_IDEA_MAC: u32 = 835;
pub const CKM_IDEA_MAC_GENERAL: u32 = 836;
pub const CKM_IDEA_CBC_PAD: u32 = 837;
pub const CKM_GENERIC_SECRET_KEY_GEN: u32 = 848;
pub const CKM_CONCATENATE_BASE_AND_KEY: u32 = 864;
pub const CKM_CONCATENATE_BASE_AND_DATA: u32 = 866;
pub const CKM_CONCATENATE_DATA_AND_BASE: u32 = 867;
pub const CKM_XOR_BASE_AND_DATA: u32 = 868;
pub const CKM_EXTRACT_KEY_FROM_KEY: u32 = 869;
pub const CKM_SSL3_PRE_MASTER_KEY_GEN: u32 = 880;
pub const CKM_SSL3_MASTER_KEY_DERIVE: u32 = 881;
pub const CKM_SSL3_KEY_AND_MAC_DERIVE: u32 = 882;
pub const CKM_SSL3_MASTER_KEY_DERIVE_DH: u32 = 883;
pub const CKM_TLS_PRE_MASTER_KEY_GEN: u32 = 884;
pub const CKM_TLS_MASTER_KEY_DERIVE: u32 = 885;
pub const CKM_TLS_KEY_AND_MAC_DERIVE: u32 = 886;
pub const CKM_TLS_MASTER_KEY_DERIVE_DH: u32 = 887;
pub const CKM_SSL3_MD5_MAC: u32 = 896;
pub const CKM_SSL3_SHA1_MAC: u32 = 897;
pub const CKM_MD5_KEY_DERIVATION: u32 = 912;
pub const CKM_MD2_KEY_DERIVATION: u32 = 913;
pub const CKM_SHA1_KEY_DERIVATION: u32 = 914;
pub const CKM_PBE_MD2_DES_CBC: u32 = 928;
pub const CKM_PBE_MD5_DES_CBC: u32 = 929;
pub const CKM_PBE_MD5_CAST_CBC: u32 = 930;
pub const CKM_PBE_MD5_CAST3_CBC: u32 = 931;
pub const CKM_PBE_MD5_CAST5_CBC: u32 = 932;
pub const CKM_PBE_MD5_CAST128_CBC: u32 = 932;
pub const CKM_PBE_SHA1_CAST5_CBC: u32 = 933;
pub const CKM_PBE_SHA1_CAST128_CBC: u32 = 933;
pub const CKM_PBE_SHA1_RC4_128: u32 = 934;
pub const CKM_PBE_SHA1_RC4_40: u32 = 935;
pub const CKM_PBE_SHA1_DES3_EDE_CBC: u32 = 936;
pub const CKM_PBE_SHA1_DES2_EDE_CBC: u32 = 937;
pub const CKM_PBE_SHA1_RC2_128_CBC: u32 = 938;
pub const CKM_PBE_SHA1_RC2_40_CBC: u32 = 939;
pub const CKM_PKCS5_PBKD2: u32 = 944;
pub const CKM_PBA_SHA1_WITH_SHA1_HMAC: u32 = 960;
pub const CKM_KEY_WRAP_LYNKS: u32 = 1024;
pub const CKM_KEY_WRAP_SET_OAEP: u32 = 1025;
pub const CKM_SKIPJACK_KEY_GEN: u32 = 4096;
pub const CKM_SKIPJACK_ECB64: u32 = 4097;
pub const CKM_SKIPJACK_CBC64: u32 = 4098;
pub const CKM_SKIPJACK_OFB64: u32 = 4099;
pub const CKM_SKIPJACK_CFB64: u32 = 4100;
pub const CKM_SKIPJACK_CFB32: u32 = 4101;
pub const CKM_SKIPJACK_CFB16: u32 = 4102;
pub const CKM_SKIPJACK_CFB8: u32 = 4103;
pub const CKM_SKIPJACK_WRAP: u32 = 4104;
pub const CKM_SKIPJACK_PRIVATE_WRAP: u32 = 4105;
pub const CKM_SKIPJACK_RELAYX: u32 = 4106;
pub const CKM_KEA_KEY_PAIR_GEN: u32 = 4112;
pub const CKM_KEA_KEY_DERIVE: u32 = 4113;
pub const CKM_FORTEZZA_TIMESTAMP: u32 = 4128;
pub const CKM_BATON_KEY_GEN: u32 = 4144;
pub const CKM_BATON_ECB128: u32 = 4145;
pub const CKM_BATON_ECB96: u32 = 4146;
pub const CKM_BATON_CBC128: u32 = 4147;
pub const CKM_BATON_COUNTER: u32 = 4148;
pub const CKM_BATON_SHUFFLE: u32 = 4149;
pub const CKM_BATON_WRAP: u32 = 4150;
pub const CKM_ECDSA_KEY_PAIR_GEN: u32 = 4160;
pub const CKM_EC_KEY_PAIR_GEN: u32 = 4160;
pub const CKM_ECDSA: u32 = 4161;
pub const CKM_ECDSA_SHA1: u32 = 4162;
pub const CKM_ECDSA_SHA224: u32 = 4163;
pub const CKM_ECDSA_SHA256: u32 = 4164;
pub const CKM_ECDSA_SHA384: u32 = 4165;
pub const CKM_ECDSA_SHA512: u32 = 4166;
pub const CKM_ECDH1_DERIVE: u32 = 4176;
pub const CKM_ECDH1_COFACTOR_DERIVE: u32 = 4177;
pub const CKM_ECMQV_DERIVE: u32 = 4178;
pub const CKM_JUNIPER_KEY_GEN: u32 = 4192;
pub const CKM_JUNIPER_ECB128: u32 = 4193;
pub const CKM_JUNIPER_CBC128: u32 = 4194;
pub const CKM_JUNIPER_COUNTER: u32 = 4195;
pub const CKM_JUNIPER_SHUFFLE: u32 = 4196;
pub const CKM_JUNIPER_WRAP: u32 = 4197;
pub const CKM_FASTHASH: u32 = 4208;
pub const CKM_AES_KEY_GEN: u32 = 4224;
pub const CKM_AES_ECB: u32 = 4225;
pub const CKM_AES_CBC: u32 = 4226;
pub const CKM_AES_MAC: u32 = 4227;
pub const CKM_AES_MAC_GENERAL: u32 = 4228;
pub const CKM_AES_CBC_PAD: u32 = 4229;
pub const CKM_AES_CTR: u32 = 4230;
pub const CKM_AES_GCM: u32 = 4231;
pub const CKM_AES_CCM: u32 = 4232;
pub const CKM_AES_CTS: u32 = 4233;
pub const CKM_BLOWFISH_KEY_GEN: u32 = 4240;
pub const CKM_BLOWFISH_CBC: u32 = 4241;
pub const CKM_TWOFISH_KEY_GEN: u32 = 4242;
pub const CKM_TWOFISH_CBC: u32 = 4243;
pub const CKM_GOSTR3410_KEY_PAIR_GEN: u32 = 4608;
pub const CKM_GOSTR3410: u32 = 4609;
pub const CKM_GOSTR3410_WITH_GOSTR3411: u32 = 4610;
pub const CKM_GOSTR3410_KEY_WRAP: u32 = 4611;
pub const CKM_GOSTR3410_DERIVE: u32 = 4612;
pub const CKM_GOSTR3411: u32 = 4624;
pub const CKM_GOSTR3411_HMAC: u32 = 4625;
pub const CKM_GOST28147_KEY_GEN: u32 = 4640;
pub const CKM_GOST28147_ECB: u32 = 4641;
pub const CKM_GOST28147: u32 = 4642;
pub const CKM_GOST28147_MAC: u32 = 4643;
pub const CKM_GOST28147_KEY_WRAP: u32 = 4644;
pub const CKM_DSA_PARAMETER_GEN: u32 = 8192;
pub const CKM_DH_PKCS_PARAMETER_GEN: u32 = 8193;
pub const CKM_X9_42_DH_PARAMETER_GEN: u32 = 8194;
pub const CKM_VENDOR_DEFINED: u32 = 2147483648;
pub const CKF_HW: u32 = 1;
pub const CKF_ENCRYPT: u32 = 256;
pub const CKF_DECRYPT: u32 = 512;
pub const CKF_DIGEST: u32 = 1024;
pub const CKF_SIGN: u32 = 2048;
pub const CKF_SIGN_RECOVER: u32 = 4096;
pub const CKF_VERIFY: u32 = 8192;
pub const CKF_VERIFY_RECOVER: u32 = 16384;
pub const CKF_GENERATE: u32 = 32768;
pub const CKF_GENERATE_KEY_PAIR: u32 = 65536;
pub const CKF_WRAP: u32 = 131072;
pub const CKF_UNWRAP: u32 = 262144;
pub const CKF_DERIVE: u32 = 524288;
pub const CKF_EXTENSION: u32 = 2147483648;
pub const CKF_EC_F_P: u32 = 1048576;
pub const CKF_EC_F_2M: u32 = 2097152;
pub const CKF_EC_ECPARAMETERS: u32 = 4194304;
pub const CKF_EC_NAMEDCURVE: u32 = 8388608;
pub const CKF_EC_UNCOMPRESS: u32 = 16777216;
pub const CKF_EC_COMPRESS: u32 = 33554432;
pub const CKF_DONT_BLOCK: u32 = 1;
pub const CKD_NULL: u32 = 1;
pub const CKG_MGF1_SHA1: u32 = 1;
pub const CKG_MGF1_SHA224: u32 = 5;
pub const CKG_MGF1_SHA256: u32 = 2;
pub const CKG_MGF1_SHA384: u32 = 3;
pub const CKG_MGF1_SHA512: u32 = 4;
pub const CKZ_DATA_SPECIFIED: u32 = 1;
pub const CKF_LIBRARY_CANT_CREATE_OS_THREADS: u32 = 1;
pub const CKF_OS_LOCKING_OK: u32 = 2;
pub const CKR_OK: u32 = 0;
pub const CKR_CANCEL: u32 = 1;
pub const CKR_HOST_MEMORY: u32 = 2;
pub const CKR_SLOT_ID_INVALID: u32 = 3;
pub const CKR_GENERAL_ERROR: u32 = 5;
pub const CKR_FUNCTION_FAILED: u32 = 6;
pub const CKR_ARGUMENTS_BAD: u32 = 7;
pub const CKR_NO_EVENT: u32 = 8;
pub const CKR_NEED_TO_CREATE_THREADS: u32 = 9;
pub const CKR_CANT_LOCK: u32 = 10;
pub const CKR_ATTRIBUTE_READ_ONLY: u32 = 16;
pub const CKR_ATTRIBUTE_SENSITIVE: u32 = 17;
pub const CKR_ATTRIBUTE_TYPE_INVALID: u32 = 18;
pub const CKR_ATTRIBUTE_VALUE_INVALID: u32 = 19;
pub const CKR_DATA_INVALID: u32 = 32;
pub const CKR_DATA_LEN_RANGE: u32 = 33;
pub const CKR_DEVICE_ERROR: u32 = 48;
pub const CKR_DEVICE_MEMORY: u32 = 49;
pub const CKR_DEVICE_REMOVED: u32 = 50;
pub const CKR_ENCRYPTED_DATA_INVALID: u32 = 64;
pub const CKR_ENCRYPTED_DATA_LEN_RANGE: u32 = 65;
pub const CKR_FUNCTION_CANCELED: u32 = 80;
pub const CKR_FUNCTION_NOT_PARALLEL: u32 = 81;
pub const CKR_FUNCTION_NOT_SUPPORTED: u32 = 84;
pub const CKR_OPERATION_CANCEL_FAILED: u32 = 514;
pub const CKR_KEY_HANDLE_INVALID: u32 = 96;
pub const CKR_KEY_SIZE_RANGE: u32 = 98;
pub const CKR_KEY_TYPE_INCONSISTENT: u32 = 99;
pub const CKR_KEY_NOT_NEEDED: u32 = 100;
pub const CKR_KEY_CHANGED: u32 = 101;
pub const CKR_KEY_NEEDED: u32 = 102;
pub const CKR_KEY_INDIGESTIBLE: u32 = 103;
pub const CKR_KEY_FUNCTION_NOT_PERMITTED: u32 = 104;
pub const CKR_KEY_NOT_WRAPPABLE: u32 = 105;
pub const CKR_KEY_UNEXTRACTABLE: u32 = 106;
pub const CKR_MECHANISM_INVALID: u32 = 112;
pub const CKR_MECHANISM_PARAM_INVALID: u32 = 113;
pub const CKR_OBJECT_HANDLE_INVALID: u32 = 130;
pub const CKR_OPERATION_ACTIVE: u32 = 144;
pub const CKR_OPERATION_NOT_INITIALIZED: u32 = 145;
pub const CKR_PIN_INCORRECT: u32 = 160;
pub const CKR_PIN_INVALID: u32 = 161;
pub const CKR_PIN_LEN_RANGE: u32 = 162;
pub const CKR_PIN_EXPIRED: u32 = 163;
pub const CKR_PIN_LOCKED: u32 = 164;
pub const CKR_SESSION_CLOSED: u32 = 176;
pub const CKR_SESSION_COUNT: u32 = 177;
pub const CKR_SESSION_HANDLE_INVALID: u32 = 179;
pub const CKR_SESSION_PARALLEL_NOT_SUPPORTED: u32 = 180;
pub const CKR_SESSION_READ_ONLY: u32 = 181;
pub const CKR_SESSION_EXISTS: u32 = 182;
pub const CKR_SESSION_READ_ONLY_EXISTS: u32 = 183;
pub const CKR_SESSION_READ_WRITE_SO_EXISTS: u32 = 184;
pub const CKR_SIGNATURE_INVALID: u32 = 192;
pub const CKR_SIGNATURE_LEN_RANGE: u32 = 193;
pub const CKR_TEMPLATE_INCOMPLETE: u32 = 208;
pub const CKR_TEMPLATE_INCONSISTENT: u32 = 209;
pub const CKR_TOKEN_NOT_PRESENT: u32 = 224;
pub const CKR_TOKEN_NOT_RECOGNIZED: u32 = 225;
pub const CKR_TOKEN_WRITE_PROTECTED: u32 = 226;
pub const CKR_UNWRAPPING_KEY_HANDLE_INVALID: u32 = 240;
pub const CKR_UNWRAPPING_KEY_SIZE_RANGE: u32 = 241;
pub const CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT: u32 = 242;
pub const CKR_USER_ALREADY_LOGGED_IN: u32 = 256;
pub const CKR_USER_NOT_LOGGED_IN: u32 = 257;
pub const CKR_USER_PIN_NOT_INITIALIZED: u32 = 258;
pub const CKR_USER_TYPE_INVALID: u32 = 259;
pub const CKR_USER_ANOTHER_ALREADY_LOGGED_IN: u32 = 260;
pub const CKR_USER_TOO_MANY_TYPES: u32 = 261;
pub const CKR_WRAPPED_KEY_INVALID: u32 = 272;
pub const CKR_WRAPPED_KEY_LEN_RANGE: u32 = 274;
pub const CKR_WRAPPING_KEY_HANDLE_INVALID: u32 = 275;
pub const CKR_WRAPPING_KEY_SIZE_RANGE: u32 = 276;
pub const CKR_WRAPPING_KEY_TYPE_INCONSISTENT: u32 = 277;
pub const CKR_RANDOM_SEED_NOT_SUPPORTED: u32 = 288;
pub const CKR_RANDOM_NO_RNG: u32 = 289;
pub const CKR_DOMAIN_PARAMS_INVALID: u32 = 304;
pub const CKR_CURVE_NOT_SUPPORTED: u32 = 320;
pub const CKR_BUFFER_TOO_SMALL: u32 = 336;
pub const CKR_SAVED_STATE_INVALID: u32 = 352;
pub const CKR_INFORMATION_SENSITIVE: u32 = 368;
pub const CKR_STATE_UNSAVEABLE: u32 = 384;
pub const CKR_CRYPTOKI_NOT_INITIALIZED: u32 = 400;
pub const CKR_CRYPTOKI_ALREADY_INITIALIZED: u32 = 401;
pub const CKR_MUTEX_BAD: u32 = 416;
pub const CKR_MUTEX_NOT_LOCKED: u32 = 417;
pub const CKR_FUNCTION_REJECTED: u32 = 512;
pub const CKR_VENDOR_DEFINED: u32 = 2147483648;
pub const CK_FALSE: u32 = 0;
pub const CK_TRUE: u32 = 1;

pub type CK_FLAGS = ::std::os::raw::c_ulong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_VERSION {
    pub major: ::std::os::raw::c_uchar,
    pub minor: ::std::os::raw::c_uchar,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_INFO {
    pub cryptokiVersion: CK_VERSION,
    pub manufacturerID: [::std::os::raw::c_uchar; 32usize],
    pub flags: CK_FLAGS,
    pub libraryDescription: [::std::os::raw::c_uchar; 32usize],
    pub libraryVersion: CK_VERSION,
}

pub type CK_NOTIFICATION = ::std::os::raw::c_ulong;
pub type CK_SLOT_ID = ::std::os::raw::c_ulong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_SLOT_INFO {
    pub slotDescription: [::std::os::raw::c_uchar; 64usize],
    pub manufacturerID: [::std::os::raw::c_uchar; 32usize],
    pub flags: CK_FLAGS,
    pub hardwareVersion: CK_VERSION,
    pub firmwareVersion: CK_VERSION,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_TOKEN_INFO {
    pub label: [::std::os::raw::c_uchar; 32usize],
    pub manufacturerID: [::std::os::raw::c_uchar; 32usize],
    pub model: [::std::os::raw::c_uchar; 16usize],
    pub serialNumber: [::std::os::raw::c_uchar; 16usize],
    pub flags: CK_FLAGS,
    pub ulMaxSessionCount: ::std::os::raw::c_ulong,
    pub ulSessionCount: ::std::os::raw::c_ulong,
    pub ulMaxRwSessionCount: ::std::os::raw::c_ulong,
    pub ulRwSessionCount: ::std::os::raw::c_ulong,
    pub ulMaxPinLen: ::std::os::raw::c_ulong,
    pub ulMinPinLen: ::std::os::raw::c_ulong,
    pub ulTotalPublicMemory: ::std::os::raw::c_ulong,
    pub ulFreePublicMemory: ::std::os::raw::c_ulong,
    pub ulTotalPrivateMemory: ::std::os::raw::c_ulong,
    pub ulFreePrivateMemory: ::std::os::raw::c_ulong,
    pub hardwareVersion: CK_VERSION,
    pub firmwareVersion: CK_VERSION,
    pub utcTime: [::std::os::raw::c_uchar; 16usize],
}

pub type CK_SESSION_HANDLE = ::std::os::raw::c_ulong;
pub type CK_USER_TYPE = ::std::os::raw::c_ulong;
pub type CK_STATE = ::std::os::raw::c_ulong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_SESSION_INFO {
    pub slotID: CK_SLOT_ID,
    pub state: CK_STATE,
    pub flags: CK_FLAGS,
    pub ulDeviceError: ::std::os::raw::c_ulong,
}

pub type CK_OBJECT_HANDLE = ::std::os::raw::c_ulong;
pub type CK_OBJECT_CLASS = ::std::os::raw::c_ulong;
pub type CK_HW_FEATURE_TYPE = ::std::os::raw::c_ulong;
pub type CK_KEY_TYPE = ::std::os::raw::c_ulong;
pub type CK_CERTIFICATE_TYPE = ::std::os::raw::c_ulong;
pub type CK_ATTRIBUTE_TYPE = ::std::os::raw::c_ulong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_ATTRIBUTE {
    pub type_: CK_ATTRIBUTE_TYPE,
    pub pValue: *mut ::std::os::raw::c_void,
    pub ulValueLen: ::std::os::raw::c_ulong,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_DATE {
    pub year: [::std::os::raw::c_uchar; 4usize],
    pub month: [::std::os::raw::c_uchar; 2usize],
    pub day: [::std::os::raw::c_uchar; 2usize],
}

pub type CK_MECHANISM_TYPE = ::std::os::raw::c_ulong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_MECHANISM {
    pub mechanism: CK_MECHANISM_TYPE,
    pub pParameter: *mut ::std::os::raw::c_void,
    pub ulParameterLen: ::std::os::raw::c_ulong,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_MECHANISM_INFO {
    pub ulMinKeySize: ::std::os::raw::c_ulong,
    pub ulMaxKeySize: ::std::os::raw::c_ulong,
    pub flags: CK_FLAGS,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_ECDH1_DERIVE_PARAMS {
    pub kdf: ::std::os::raw::c_ulong,
    pub ulSharedDataLen: ::std::os::raw::c_ulong,
    pub pSharedData: *mut ::std::os::raw::c_uchar,
    pub ulPublicDataLen: ::std::os::raw::c_ulong,
    pub pPublicData: *mut ::std::os::raw::c_uchar,
}

pub type CK_RSA_PKCS_MGF_TYPE = ::std::os::raw::c_ulong;
pub type CK_RSA_PKCS_OAEP_SOURCE_TYPE = ::std::os::raw::c_ulong;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_RSA_PKCS_OAEP_PARAMS {
    pub hashAlg: CK_MECHANISM_TYPE,
    pub mgf: CK_RSA_PKCS_MGF_TYPE,
    pub source: CK_RSA_PKCS_OAEP_SOURCE_TYPE,
    pub pSourceData: *mut ::std::os::raw::c_void,
    pub ulSourceDataLen: ::std::os::raw::c_ulong,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_RSA_PKCS_PSS_PARAMS {
    pub hashAlg: CK_MECHANISM_TYPE,
    pub mgf: CK_RSA_PKCS_MGF_TYPE,
    pub sLen: ::std::os::raw::c_ulong,
}

pub type CK_RV = ::std::os::raw::c_ulong;

pub type CK_NOTIFY = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        event: CK_NOTIFICATION,
        application: *mut ::std::os::raw::c_void,
    ) -> CK_RV,
>;

pub type CK_C_Initialize =
    ::std::option::Option<extern "C" fn(init_args: *mut CK_C_INITIALIZE_ARGS) -> CK_RV>;

pub type CK_C_Finalize =
    ::std::option::Option<extern "C" fn(pReserved: *mut ::std::os::raw::c_void) -> CK_RV>;

pub type CK_C_GetInfo = ::std::option::Option<unsafe extern "C" fn(info: *mut CK_INFO) -> CK_RV>;

pub type CK_C_GetFunctionList =
    ::std::option::Option<unsafe extern "C" fn(function_list: *mut *mut CK_FUNCTION_LIST) -> CK_RV>;

pub type CK_C_GetSlotList = ::std::option::Option<
    unsafe extern "C" fn(
        token_present: ::std::os::raw::c_uchar,
        slot_list: *mut CK_SLOT_ID,
        count: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GetSlotInfo = ::std::option::Option<
    unsafe extern "C" fn(slotID: CK_SLOT_ID, info: *mut CK_SLOT_INFO) -> CK_RV,
>;

pub type CK_C_GetTokenInfo = ::std::option::Option<
    unsafe extern "C" fn(slotID: CK_SLOT_ID, info: *mut CK_TOKEN_INFO) -> CK_RV,
>;

pub type CK_C_WaitForSlotEvent = ::std::option::Option<
    unsafe extern "C" fn(
        flags: CK_FLAGS,
        slot: *mut CK_SLOT_ID,
        pReserved: *mut ::std::os::raw::c_void,
    ) -> CK_RV,
>;

pub type CK_C_GetMechanismList = ::std::option::Option<
    unsafe extern "C" fn(
        slotID: CK_SLOT_ID,
        mechanism_list: *mut CK_MECHANISM_TYPE,
        count: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GetMechanismInfo = ::std::option::Option<
    unsafe extern "C" fn(
        slotID: CK_SLOT_ID,
        type_: CK_MECHANISM_TYPE,
        info: *mut CK_MECHANISM_INFO,
    ) -> CK_RV,
>;

pub type CK_C_InitToken = ::std::option::Option<
    unsafe extern "C" fn(
        slotID: CK_SLOT_ID,
        pin: *mut ::std::os::raw::c_uchar,
        pin_len: ::std::os::raw::c_ulong,
        label: *mut ::std::os::raw::c_uchar,
    ) -> CK_RV,
>;

pub type CK_C_InitPIN = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        pin: *mut ::std::os::raw::c_uchar,
        pin_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SetPIN = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        old_pin: *mut ::std::os::raw::c_uchar,
        old_len: ::std::os::raw::c_ulong,
        new_pin: *mut ::std::os::raw::c_uchar,
        new_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_OpenSession = ::std::option::Option<
    unsafe extern "C" fn(
        slotID: CK_SLOT_ID,
        flags: CK_FLAGS,
        application: *mut ::std::os::raw::c_void,
        notify: CK_NOTIFY,
        session: *mut CK_SESSION_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_CloseSession =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_CloseAllSessions =
    ::std::option::Option<unsafe extern "C" fn(slotID: CK_SLOT_ID) -> CK_RV>;

pub type CK_C_GetSessionInfo = ::std::option::Option<
    unsafe extern "C" fn(session: CK_SESSION_HANDLE, info: *mut CK_SESSION_INFO) -> CK_RV,
>;

pub type CK_C_GetOperationState = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        operation_state: *mut ::std::os::raw::c_uchar,
        operation_state_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SetOperationState = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        operation_state: *mut ::std::os::raw::c_uchar,
        operation_state_len: ::std::os::raw::c_ulong,
        encryption_key: CK_OBJECT_HANDLE,
        authentiation_key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_Login = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        user_type: CK_USER_TYPE,
        pin: *mut ::std::os::raw::c_uchar,
        pin_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_Logout =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_CreateObject = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        count: ::std::os::raw::c_ulong,
        object: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_CopyObject = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        object: CK_OBJECT_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        count: ::std::os::raw::c_ulong,
        new_object: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_DestroyObject = ::std::option::Option<
    unsafe extern "C" fn(session: CK_SESSION_HANDLE, object: CK_OBJECT_HANDLE) -> CK_RV,
>;

pub type CK_C_GetObjectSize = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        object: CK_OBJECT_HANDLE,
        size: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GetAttributeValue = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        object: CK_OBJECT_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        count: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SetAttributeValue = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        object: CK_OBJECT_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        count: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_FindObjectsInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        count: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_FindObjects = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        object: *mut CK_OBJECT_HANDLE,
        max_object_count: ::std::os::raw::c_ulong,
        object_count: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_FindObjectsFinal =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_EncryptInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_Encrypt = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        encrypted_data: *mut ::std::os::raw::c_uchar,
        encrypted_data_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_EncryptUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
        encrypted_part: *mut ::std::os::raw::c_uchar,
        encrypted_part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_EncryptFinal = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        last_encrypted_part: *mut ::std::os::raw::c_uchar,
        last_encrypted_part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DecryptInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_Decrypt = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        encrypted_data: *mut ::std::os::raw::c_uchar,
        encrypted_data_len: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DecryptUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        encrypted_part: *mut ::std::os::raw::c_uchar,
        encrypted_part_len: ::std::os::raw::c_ulong,
        part: *mut ::std::os::raw::c_uchar,
        part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DecryptFinal = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        last_part: *mut ::std::os::raw::c_uchar,
        last_part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DigestInit = ::std::option::Option<
    unsafe extern "C" fn(session: CK_SESSION_HANDLE, mechanism: *mut CK_MECHANISM) -> CK_RV,
>;

pub type CK_C_Digest = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        digest: *mut ::std::os::raw::c_uchar,
        digest_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DigestUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DigestKey = ::std::option::Option<
    unsafe extern "C" fn(session: CK_SESSION_HANDLE, key: CK_OBJECT_HANDLE) -> CK_RV,
>;

pub type CK_C_DigestFinal = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        digest: *mut ::std::os::raw::c_uchar,
        digest_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SignInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_Sign = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SignUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SignFinal = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SignRecoverInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_SignRecover = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_VerifyInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_Verify = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_VerifyUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_VerifyFinal = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_VerifyRecoverInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_VerifyRecover = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DigestEncryptUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
        encrypted_part: *mut ::std::os::raw::c_uchar,
        encrypted_part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DecryptDigestUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        encrypted_part: *mut ::std::os::raw::c_uchar,
        encrypted_part_len: ::std::os::raw::c_ulong,
        part: *mut ::std::os::raw::c_uchar,
        part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SignEncryptUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
        encrypted_part: *mut ::std::os::raw::c_uchar,
        encrypted_part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_DecryptVerifyUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        encrypted_part: *mut ::std::os::raw::c_uchar,
        encrypted_part_len: ::std::os::raw::c_ulong,
        part: *mut ::std::os::raw::c_uchar,
        part_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GenerateKey = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        templ: *mut CK_ATTRIBUTE,
        count: ::std::os::raw::c_ulong,
        key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_GenerateKeyPair = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        public_key_template: *mut CK_ATTRIBUTE,
        public_key_attribute_count: ::std::os::raw::c_ulong,
        private_key_template: *mut CK_ATTRIBUTE,
        private_key_attribute_count: ::std::os::raw::c_ulong,
        public_key: *mut CK_OBJECT_HANDLE,
        private_key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_WrapKey = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        wrapping_key: CK_OBJECT_HANDLE,
        key: CK_OBJECT_HANDLE,
        wrapped_key: *mut ::std::os::raw::c_uchar,
        wrapped_key_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_UnwrapKey = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        unwrapping_key: CK_OBJECT_HANDLE,
        wrapped_key: *mut ::std::os::raw::c_uchar,
        wrapped_key_len: ::std::os::raw::c_ulong,
        templ: *mut CK_ATTRIBUTE,
        attribute_count: ::std::os::raw::c_ulong,
        key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_DeriveKey = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        base_key: CK_OBJECT_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        attribute_count: ::std::os::raw::c_ulong,
        key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

pub type CK_C_SeedRandom = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        seed: *mut ::std::os::raw::c_uchar,
        seed_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GenerateRandom = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        random_data: *mut ::std::os::raw::c_uchar,
        random_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GetFunctionStatus =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_CancelFunction =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_GetInterfaceList = ::std::option::Option<
    unsafe extern "C" fn(
        interfaces_list: *mut CK_INTERFACE,
        count: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_GetInterface = ::std::option::Option<
    unsafe extern "C" fn(
        interface_name: *mut ::std::os::raw::c_uchar,
        version: *mut CK_VERSION,
        interface_: *mut *mut CK_INTERFACE,
        flags: CK_FLAGS,
    ) -> CK_RV,
>;

pub type CK_C_LoginUser = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        user_type: CK_USER_TYPE,
        pin: *mut ::std::os::raw::c_uchar,
        pin_len: ::std::os::raw::c_ulong,
        username: *mut ::std::os::raw::c_uchar,
        username_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;

pub type CK_C_SessionCancel = ::std::option::Option<
    unsafe extern "C" fn(session: CK_SESSION_HANDLE, flags: CK_FLAGS) -> CK_RV,
>;

pub type CK_C_MessageEncryptInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_EncryptMessage = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        associated_data: *mut ::std::os::raw::c_uchar,
        associated_data_len: ::std::os::raw::c_ulong,
        plaintext: *mut ::std::os::raw::c_uchar,
        plaintext_len: ::std::os::raw::c_ulong,
        ciphertext: *mut ::std::os::raw::c_uchar,
        ciphertext_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_EncryptMessageBegin = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        associated_data: *mut ::std::os::raw::c_uchar,
        associated_data_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_EncryptMessageNext = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        plaintext_part: *mut ::std::os::raw::c_uchar,
        plaintext_part_len: ::std::os::raw::c_ulong,
        ciphertext_part: *mut ::std::os::raw::c_uchar,
        ciphertext_part_len: *mut ::std::os::raw::c_ulong,
        flags: CK_FLAGS,
    ) -> CK_RV,
>;
pub type CK_C_MessageEncryptFinal =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_MessageDecryptInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_DecryptMessage = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        associated_data: *mut ::std::os::raw::c_uchar,
        associated_data_len: ::std::os::raw::c_ulong,
        ciphertext: *mut ::std::os::raw::c_uchar,
        ciphertext_len: ::std::os::raw::c_ulong,
        plaintext: *mut ::std::os::raw::c_uchar,
        plaintext_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_DecryptMessageBegin = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        associated_data: *mut ::std::os::raw::c_uchar,
        associated_data_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_DecryptMessageNext = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        ciphertext_part: *mut ::std::os::raw::c_uchar,
        ciphertext_part_len: ::std::os::raw::c_ulong,
        plaintext_part: *mut ::std::os::raw::c_uchar,
        plaintext_part_len: *mut ::std::os::raw::c_ulong,
        flags: CK_FLAGS,
    ) -> CK_RV,
>;
pub type CK_C_MessageDecryptFinal =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_MessageSignInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_SignMessage = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_SignMessageBegin = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_SignMessageNext = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_MessageSignFinal =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_MessageVerifyInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_VerifyMessage = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_VerifyMessageBegin = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_VerifyMessageNext = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        parameter: *mut ::std::os::raw::c_void,
        parameter_len: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_MessageVerifyFinal =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;

pub type CK_C_EncapsulateKey = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        public_key: CK_OBJECT_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        attribute_count: ::std::os::raw::c_ulong,
        ciphertext: *mut ::std::os::raw::c_uchar,
        ciphertext_len: *mut ::std::os::raw::c_ulong,
        key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_DecapsulateKey = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        private_key: CK_OBJECT_HANDLE,
        templ: *mut CK_ATTRIBUTE,
        attribute_count: ::std::os::raw::c_ulong,
        ciphertext: *mut ::std::os::raw::c_uchar,
        ciphertext_len: *mut ::std::os::raw::c_ulong,
        key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;
pub type CK_C_VerifySignatureInit = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        key: CK_OBJECT_HANDLE,
        signature: *mut ::std::os::raw::c_uchar,
        signature_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_VerifySignature = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_VerifySignatureUpdate = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        part: *mut ::std::os::raw::c_uchar,
        part_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_VerifySignatureFinal =
    ::std::option::Option<unsafe extern "C" fn(session: CK_SESSION_HANDLE) -> CK_RV>;
pub type CK_C_GetSessionValidationFlags = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        type_: CK_SESSION_VALIDATION_FLAGS_TYPE,
        flags: *mut CK_FLAGS,
    ) -> CK_RV,
>;
pub type CK_C_AsyncComplete = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        function_name: *mut ::std::os::raw::c_uchar,
        result: *mut CK_ASYNC_DATA,
    ) -> CK_RV,
>;
pub type CK_C_AsyncGetID = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        function_name: *mut ::std::os::raw::c_uchar,
        id: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_AsyncJoin = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        function_name: *mut ::std::os::raw::c_uchar,
        id: ::std::os::raw::c_ulong,
        data: *mut ::std::os::raw::c_uchar,
        data_len: ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_WrapKeyAuthenticated = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        wrapping_key: CK_OBJECT_HANDLE,
        key: CK_OBJECT_HANDLE,
        associated_data: *mut ::std::os::raw::c_uchar,
        associated_data_len: ::std::os::raw::c_ulong,
        wrapped_key: *mut ::std::os::raw::c_uchar,
        wrapped_key_len: *mut ::std::os::raw::c_ulong,
    ) -> CK_RV,
>;
pub type CK_C_UnwrapKeyAuthenticated = ::std::option::Option<
    unsafe extern "C" fn(
        session: CK_SESSION_HANDLE,
        mechanism: *mut CK_MECHANISM,
        unwrapping_key: CK_OBJECT_HANDLE,
        wrapped_key: *mut ::std::os::raw::c_uchar,
        wrapped_key_len: ::std::os::raw::c_ulong,
        templ: *mut CK_ATTRIBUTE,
        attribute_count: ::std::os::raw::c_ulong,
        associated_data: *mut ::std::os::raw::c_uchar,
        associated_data_len: ::std::os::raw::c_ulong,
        key: *mut CK_OBJECT_HANDLE,
    ) -> CK_RV,
>;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_INTERFACE {
    pub pInterfaceName: *mut ::std::os::raw::c_char,
    pub pFunctionList: *mut ::std::os::raw::c_void,
    pub flags: CK_FLAGS,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_ASYNC_DATA {
    pub ulVersionNum: ::std::os::raw::c_ulong,
    pub pValue: *mut ::std::os::raw::c_uchar,
    pub ulValueLen: ::std::os::raw::c_ulong,
    pub hObject: CK_OBJECT_HANDLE,
    pub hAdditionalObject: CK_OBJECT_HANDLE,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_FUNCTION_LIST {
    pub version: CK_VERSION,
    pub C_Initialize: CK_C_Initialize,
    pub C_Finalize: CK_C_Finalize,
    pub C_GetInfo: CK_C_GetInfo,
    pub C_GetFunctionList: CK_C_GetFunctionList,
    pub C_GetSlotList: CK_C_GetSlotList,
    pub C_GetSlotInfo: CK_C_GetSlotInfo,
    pub C_GetTokenInfo: CK_C_GetTokenInfo,
    pub C_GetMechanismList: CK_C_GetMechanismList,
    pub C_GetMechanismInfo: CK_C_GetMechanismInfo,
    pub C_InitToken: CK_C_InitToken,
    pub C_InitPIN: CK_C_InitPIN,
    pub C_SetPIN: CK_C_SetPIN,
    pub C_OpenSession: CK_C_OpenSession,
    pub C_CloseSession: CK_C_CloseSession,
    pub C_CloseAllSessions: CK_C_CloseAllSessions,
    pub C_GetSessionInfo: CK_C_GetSessionInfo,
    pub C_GetOperationState: CK_C_GetOperationState,
    pub C_SetOperationState: CK_C_SetOperationState,
    pub C_Login: CK_C_Login,
    pub C_Logout: CK_C_Logout,
    pub C_CreateObject: CK_C_CreateObject,
    pub C_CopyObject: CK_C_CopyObject,
    pub C_DestroyObject: CK_C_DestroyObject,
    pub C_GetObjectSize: CK_C_GetObjectSize,
    pub C_GetAttributeValue: CK_C_GetAttributeValue,
    pub C_SetAttributeValue: CK_C_SetAttributeValue,
    pub C_FindObjectsInit: CK_C_FindObjectsInit,
    pub C_FindObjects: CK_C_FindObjects,
    pub C_FindObjectsFinal: CK_C_FindObjectsFinal,
    pub C_EncryptInit: CK_C_EncryptInit,
    pub C_Encrypt: CK_C_Encrypt,
    pub C_EncryptUpdate: CK_C_EncryptUpdate,
    pub C_EncryptFinal: CK_C_EncryptFinal,
    pub C_DecryptInit: CK_C_DecryptInit,
    pub C_Decrypt: CK_C_Decrypt,
    pub C_DecryptUpdate: CK_C_DecryptUpdate,
    pub C_DecryptFinal: CK_C_DecryptFinal,
    pub C_DigestInit: CK_C_DigestInit,
    pub C_Digest: CK_C_Digest,
    pub C_DigestUpdate: CK_C_DigestUpdate,
    pub C_DigestKey: CK_C_DigestKey,
    pub C_DigestFinal: CK_C_DigestFinal,
    pub C_SignInit: CK_C_SignInit,
    pub C_Sign: CK_C_Sign,
    pub C_SignUpdate: CK_C_SignUpdate,
    pub C_SignFinal: CK_C_SignFinal,
    pub C_SignRecoverInit: CK_C_SignRecoverInit,
    pub C_SignRecover: CK_C_SignRecover,
    pub C_VerifyInit: CK_C_VerifyInit,
    pub C_Verify: CK_C_Verify,
    pub C_VerifyUpdate: CK_C_VerifyUpdate,
    pub C_VerifyFinal: CK_C_VerifyFinal,
    pub C_VerifyRecoverInit: CK_C_VerifyRecoverInit,
    pub C_VerifyRecover: CK_C_VerifyRecover,
    pub C_DigestEncryptUpdate: CK_C_DigestEncryptUpdate,
    pub C_DecryptDigestUpdate: CK_C_DecryptDigestUpdate,
    pub C_SignEncryptUpdate: CK_C_SignEncryptUpdate,
    pub C_DecryptVerifyUpdate: CK_C_DecryptVerifyUpdate,
    pub C_GenerateKey: CK_C_GenerateKey,
    pub C_GenerateKeyPair: CK_C_GenerateKeyPair,
    pub C_WrapKey: CK_C_WrapKey,
    pub C_UnwrapKey: CK_C_UnwrapKey,
    pub C_DeriveKey: CK_C_DeriveKey,
    pub C_SeedRandom: CK_C_SeedRandom,
    pub C_GenerateRandom: CK_C_GenerateRandom,
    pub C_GetFunctionStatus: CK_C_GetFunctionStatus,
    pub C_CancelFunction: CK_C_CancelFunction,
    pub C_WaitForSlotEvent: CK_C_WaitForSlotEvent,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_FUNCTION_LIST_3_0 {
    pub base: CK_FUNCTION_LIST,
    pub C_GetInterfaceList: CK_C_GetInterfaceList,
    pub C_GetInterface: CK_C_GetInterface,
    pub C_LoginUser: CK_C_LoginUser,
    pub C_SessionCancel: CK_C_SessionCancel,
    pub C_MessageEncryptInit: CK_C_MessageEncryptInit,
    pub C_EncryptMessage: CK_C_EncryptMessage,
    pub C_EncryptMessageBegin: CK_C_EncryptMessageBegin,
    pub C_EncryptMessageNext: CK_C_EncryptMessageNext,
    pub C_MessageEncryptFinal: CK_C_MessageEncryptFinal,
    pub C_MessageDecryptInit: CK_C_MessageDecryptInit,
    pub C_DecryptMessage: CK_C_DecryptMessage,
    pub C_DecryptMessageBegin: CK_C_DecryptMessageBegin,
    pub C_DecryptMessageNext: CK_C_DecryptMessageNext,
    pub C_MessageDecryptFinal: CK_C_MessageDecryptFinal,
    pub C_MessageSignInit: CK_C_MessageSignInit,
    pub C_SignMessage: CK_C_SignMessage,
    pub C_SignMessageBegin: CK_C_SignMessageBegin,
    pub C_SignMessageNext: CK_C_SignMessageNext,
    pub C_MessageSignFinal: CK_C_MessageSignFinal,
    pub C_MessageVerifyInit: CK_C_MessageVerifyInit,
    pub C_VerifyMessage: CK_C_VerifyMessage,
    pub C_VerifyMessageBegin: CK_C_VerifyMessageBegin,
    pub C_VerifyMessageNext: CK_C_VerifyMessageNext,
    pub C_MessageVerifyFinal: CK_C_MessageVerifyFinal,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_FUNCTION_LIST_3_2 {
    pub base: CK_FUNCTION_LIST_3_0,
    pub C_EncapsulateKey: CK_C_EncapsulateKey,
    pub C_DecapsulateKey: CK_C_DecapsulateKey,
    pub C_VerifySignatureInit: CK_C_VerifySignatureInit,
    pub C_VerifySignature: CK_C_VerifySignature,
    pub C_VerifySignatureUpdate: CK_C_VerifySignatureUpdate,
    pub C_VerifySignatureFinal: CK_C_VerifySignatureFinal,
    pub C_GetSessionValidationFlags: CK_C_GetSessionValidationFlags,
    pub C_AsyncComplete: CK_C_AsyncComplete,
    pub C_AsyncGetID: CK_C_AsyncGetID,
    pub C_AsyncJoin: CK_C_AsyncJoin,
    pub C_WrapKeyAuthenticated: CK_C_WrapKeyAuthenticated,
    pub C_UnwrapKeyAuthenticated: CK_C_UnwrapKeyAuthenticated,
}

impl ::std::ops::Deref for CK_FUNCTION_LIST_3_0 {
    type Target = CK_FUNCTION_LIST;

    fn deref(&self) -> &Self::Target {
        &self.base
    }
}

impl ::std::ops::Deref for CK_FUNCTION_LIST_3_2 {
    type Target = CK_FUNCTION_LIST_3_0;

    fn deref(&self) -> &Self::Target {
        &self.base
    }
}

pub type CK_CREATEMUTEX =
    ::std::option::Option<unsafe extern "C" fn(mutex: *mut *mut ::std::os::raw::c_void) -> CK_RV>;
pub type CK_DESTROYMUTEX =
    ::std::option::Option<unsafe extern "C" fn(mutex: *mut ::std::os::raw::c_void) -> CK_RV>;
pub type CK_LOCKMUTEX =
    ::std::option::Option<unsafe extern "C" fn(mutex: *mut ::std::os::raw::c_void) -> CK_RV>;
pub type CK_UNLOCKMUTEX =
    ::std::option::Option<unsafe extern "C" fn(mutex: *mut ::std::os::raw::c_void) -> CK_RV>;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CK_C_INITIALIZE_ARGS {
    pub pfnCreateMutex: CK_CREATEMUTEX,
    pub pfnDestroyMutex: CK_DESTROYMUTEX,
    pub pfnLockMutex: CK_LOCKMUTEX,
    pub pfnUnlockMutex: CK_UNLOCKMUTEX,
    pub flags: CK_FLAGS,
    pub pReserved: *mut ::std::os::raw::c_void,
}

pub type CK_BYTE = ::std::os::raw::c_uchar;
pub type CK_CHAR = ::std::os::raw::c_uchar;
pub type CK_UTF8CHAR = ::std::os::raw::c_uchar;
pub type CK_BBOOL = ::std::os::raw::c_uchar;
pub type CK_ULONG = ::std::os::raw::c_ulong;
pub type CK_LONG = ::std::os::raw::c_long;
pub type CK_BYTE_PTR = *mut CK_BYTE;
pub type CK_CHAR_PTR = *mut CK_CHAR;
pub type CK_UTF8CHAR_PTR = *mut CK_UTF8CHAR;
pub type CK_ULONG_PTR = *mut CK_ULONG;
pub type CK_VOID_PTR = *mut ::std::os::raw::c_void;
pub type CK_VOID_PTR_PTR = *mut *mut ::std::os::raw::c_void;
pub type CK_VERSION_PTR = *mut CK_VERSION;
pub type CK_INFO_PTR = *mut CK_INFO;
pub type CK_SLOT_ID_PTR = *mut CK_SLOT_ID;
pub type CK_SLOT_INFO_PTR = *mut CK_SLOT_INFO;
pub type CK_TOKEN_INFO_PTR = *mut CK_TOKEN_INFO;
pub type CK_SESSION_HANDLE_PTR = *mut CK_SESSION_HANDLE;
pub type CK_SESSION_INFO_PTR = *mut CK_SESSION_INFO;
pub type CK_OBJECT_HANDLE_PTR = *mut CK_OBJECT_HANDLE;
pub type CK_OBJECT_CLASS_PTR = *mut CK_OBJECT_CLASS;
pub type CK_ATTRIBUTE_PTR = *mut CK_ATTRIBUTE;
pub type CK_DATE_PTR = *mut CK_DATE;
pub type CK_MECHANISM_TYPE_PTR = *mut CK_MECHANISM_TYPE;
pub type CK_MECHANISM_PTR = *mut CK_MECHANISM;
pub type CK_MECHANISM_INFO_PTR = *mut CK_MECHANISM_INFO;
pub type CK_SESSION_VALIDATION_FLAGS_TYPE = ::std::os::raw::c_ulong;
pub type CK_SESSION_VALIDATION_FLAGS_TYPE_PTR = *mut CK_SESSION_VALIDATION_FLAGS_TYPE;
pub type CK_INTERFACE_PTR = *mut CK_INTERFACE;
pub type CK_INTERFACE_PTR_PTR = *mut *mut CK_INTERFACE;
pub type CK_FUNCTION_LIST_PTR = *mut CK_FUNCTION_LIST;
pub type CK_FUNCTION_LIST_PTR_PTR = *mut *mut CK_FUNCTION_LIST;
pub type CK_FUNCTION_LIST_3_0_PTR = *mut CK_FUNCTION_LIST_3_0;
pub type CK_FUNCTION_LIST_3_0_PTR_PTR = *mut *mut CK_FUNCTION_LIST_3_0;
pub type CK_FUNCTION_LIST_3_2_PTR = *mut CK_FUNCTION_LIST_3_2;
pub type CK_FUNCTION_LIST_3_2_PTR_PTR = *mut *mut CK_FUNCTION_LIST_3_2;
pub type CK_ASYNC_DATA_PTR = *mut CK_ASYNC_DATA;
pub type CK_C_INITIALIZE_ARGS_PTR = *mut CK_C_INITIALIZE_ARGS;
